# Italian COVID Library Tutorial

Welcome to the Italian COVID Library tutorial, which shall guide you through the use of this library.

## Getting Started with Italian COVID Library

Before starting, make sure you have installed Italian COVID Library as shown in README.md or the GitHub project homepage.

Whenever you want to use Italian COVID Library in your code, just import it:

In [1]:
import itacovidlib.icl_functions as icl

You are now ready to use the full library.
The library functions are divided into "getter" functions (the ones whose name starts with "get"), "teller" functions (name starting with "tell") and "map plotter" functions (plot_on_map and prepare_for_plotting_on_map).

The following shows the full list of functions per category and in alphabetical order. The complete manual page for each function can be shown with one of these two options (for, as an example, tell_total_vaccinated):

In [2]:
help(icl.tell_total_vaccinated)

Help on function tell_total_vaccinated in module itacovidlib.icl_functions:

tell_total_vaccinated(dose_number, option='n')
    Depending on the int value provided as dose_number:
    dose_number = 1: returns the number of individuals who have been injected at least one vaccine dose in Italy (independently of it being enough for vaccination cycle completion, as is the case with Janssen vaccine or for individuals with recent COVID-19 injection, for whom only one dose is required;
    dose_number = 2: returns the number of individuals who have completed the vaccination cycle in Italy (with double dose for Pfizer/BioNTech, Moderna and Vaxzevria (AstraZeneca), with single dose for Janssen, with single dose for individuals previously infected with COVID-19 between 3 and 6 months before vaccination;
    dose_number = 3: returns the number of individuals who have been injected an extra dose of vaccine in Italy, being eligible for it depending on their medical condition (commonly referred to as "third dose" in media).

    Result is returned, depending on the str value provided as option:
    no option or option = "n" or "number": just returns the requested number (default option);
    option = "o" or "over12": returns the requested number as a fraction of the Italian population aged over 12;
    option = "p" or "population": returns the requested number as a fraction of the whole Italian population.

    Parameters
    ----------
    dose_number : int
        Dose number of interest. See above for the meaning of dose_number = 1, 2 or 3. Other int values yield an error.

    option : str
        Output option. See above for the meaning of the various option codes. Other str values yield an error.

    Raises
    ------
    ItaCovidLibConnectionError
        Raised when there are issues with Internet connection.

    ItaCovidLibArgumentError
        Raised when improper arguments are passed to the function.

    Returns
    -------
    FOR THE DEFAULT OPTION:
    numpy.int64
        NumPy integer (see above for its meaning, depending on dose_number code).

    FOR THE OTHER OPTIONS:
    numpy.float64
        NumPy floating point (see above for its meaning, depending on dose_number code and option code).

    See Also
    --------
    get_vaccine_admin : full data about vaccine administration in Italy

In [3]:
icl.tell_total_vaccinated?

## Getter Functions ("get_")

Getter functions are functions which retrieve directly **raw data** about COVID19 infections and vaccinations from the official governmental databases, making them available to the user in the form of **Pandas DataFrames**. The returned object can then be handled as any normal DataFrame with the instruments of the Pandas library.
Some data (e.g. the amount of total vaccinated people) are not returned by Getter functions but by Teller functions (head to the Teller functions section to see why and how to get those data).

### get_admin_sites

Returns a DataFrame about COVID-19 vaccine administration points in Italy.

In [4]:
icl.get_admin_sites()

,region_code,province,municipality,place,NUTS1_code,NUTS2_code,ISTAT_region_code,region
0,ABR,CHIETI,CHIETI,PRESIDIO OSPEDALIERO SS ANNUNZIATA,ITF,ITF1,13,Abruzzo
1,ABR,CHIETI,LANCIANO,PRESIDIO OSPEDALIERO RENZETTI,ITF,ITF1,13,Abruzzo
2,ABR,CHIETI,VASTO,PRESIDIO OSPEDALIERO SAN PIO,ITF,ITF1,13,Abruzzo
3,ABR,L'AQUILA,AVEZZANO,P.O. SS. FILIPPO E NICOLA,ITF,ITF1,13,Abruzzo
4,ABR,L'AQUILA,L'AQUILA,PRESIDIO OSPEDALIERO SAN SALVATORE,ITF,ITF1,13,Abruzzo
...,...,...,...,...,...,...,...,...
288,VEN,ROVIGO,ROVIGO,"OSPEDALE ""SANTA MARIA DELLA MISERICORDIA""",ITH,ITH3,5,Veneto
289,VEN,TREVISO,VITTORIO VENETO,OSPEDALE DI VITTORIO VENETO,ITH,ITH3,5,Veneto
290,VEN,VENEZIA,VENEZIA MESTRE,OSPEDALE DELL'ANGELO,ITH,ITH3,5,Veneto
291,VEN,VERONA,VERONA,AZIENDA OSPEDALIERA UNIVERSITARIA INTEGRATA DI...,ITH,ITH3,5,Veneto
292,VEN,VICENZA,VICENZA,OSPEDALE DI VICENZA,ITH,ITH3,5,Veneto

### get_admin_sites_types

Returns a DataFrame about the types of COVID-19 vaccine administration points in Italy.

In [5]:
icl.get_admin_sites_types()

,region_code,place,type,NUTS1_code,NUTS2_code,ISTAT_region_code,region
0,ABR,ASP1-TERAMO-CASA DI RIPOSO-DE BENEDICTIS,Territoriale,ITF,ITF1,13,Abruzzo
1,ABR,AVEZZANO-SULMONA-L'AQUILA,Ospedaliero,ITF,ITF1,13,Abruzzo
2,ABR,CASA DI CURA PIERANGELI,Ospedaliero,ITF,ITF1,13,Abruzzo
3,ABR,CASA DI CURA VILLA SERENA,Ospedaliero,ITF,ITF1,13,Abruzzo
4,ABR,CDC S.CAMILLA-C.RIA.VILLA PINI,Territoriale,ITF,ITF1,13,Abruzzo
...,...,...,...,...,...,...,...
2884,VEN,PSR MOBY DICK,Territoriale,ITH,ITH3,5,Veneto
2885,VEN,PSR NO PROBLEM COOP. STUDIO PROGETTO,Territoriale,ITH,ITH3,5,Veneto
2886,VEN,RES.ASS.TOSS. - COMUNITA' CONTATTO - CEIS DON ...,Territoriale,ITH,ITH3,5,Veneto
2887,VEN,RES.ASS.TOSS.-CASA AURORA VENEZIA,Territoriale,ITH,ITH3,5,Veneto
2888,VEN,"RSA ""NOI CON VOI"" - MOGLIANO VENETO",Territoriale,ITH,ITH3,5,Veneto

### get_eligible

Returns a DataFrame about eligible individuals for COVID-19 vaccine administration in Italy.

In [6]:
icl.get_eligible()

    region_code   region age_group  population
0           ABR  Abruzzo     12-19       94727
1           ABR  Abruzzo     20-29      125230
2           ABR  Abruzzo     30-39      146965
3           ABR  Abruzzo     40-49      187162
4           ABR  Abruzzo     50-59      208686
..          ...      ...       ...         ...
163         VEN   Veneto     40-49      717331
164         VEN   Veneto     50-59      806474
165         VEN   Veneto     60-69      610635
166         VEN   Veneto     70-79      494721
167         VEN   Veneto       80+      368984

[168 rows x 4 columns]

### get_national_trend

Returns a DataFrame about the COVID-19 pandemic situation in Italy at a national scale.

In [7]:
icl.get_national_trend()

,date,country,hospitalized_with_symptoms,intensive_care,hospitalized,isolation,cases,cases_variation,new_cases,recovered_released,...,swabs,tested,notes,intensive_care_in,test_notes,case_notes,molecular_test_cases,antigen_test_cases,molecular_tests,antigen_tests
0,2020-02-24T18:00:00,ITA,101,26,127,94,221,0,221,1,...,4324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,ITA,114,35,150,162,311,90,93,1,...,8623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-26T18:00:00,ITA,128,36,164,221,385,74,78,3,...,9587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-27T18:00:00,ITA,248,56,304,284,588,203,250,45,...,12014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-28T18:00:00,ITA,345,64,409,412,821,233,238,46,...,15695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,2021-10-01T17:00:00,ITA,3118,429,3547,90105,93652,-656,3405,4451133,...,92759111,34310886.0,NaN,20.0,NaN,NaN,4504170.0,171588.0,60259807.0,32499304.0
586,2021-10-02T17:00:00,ITA,3057,432,3489,89260,92749,-903,3312,4455320,...,93115007,34378233.0,NaN,27.0,NaN,NaN,4507291.0,171776.0,60372560.0,32742447.0
587,2021-10-03T17:00:00,ITA,2991,431,3422,89545,92967,218,2968,4458036,...,93400967,34432558.0,NaN,21.0,NaN,NaN,4510102.0,171932.0,60459617.0,32941350.0
588,2021-10-04T17:00:00,ITA,3032,437,3469,88627,92096,-871,1612,4460482,...,93523181,34458627.0,NaN,22.0,NaN,NaN,4511622.0,172024.0,60510390.0,33012791.0
589,2021-10-05T17:00:00,ITA,2968,433,3401,86898,90299,-1797,2466,4464692,...,93845463,34515695.0,NaN,18.0,NaN,NaN,4513785.0,172324.0,60615507.0,33229956.0

### get_vaccine_admin

Returns a DataFrame about COVID-19 vaccine administration in Italy.

In [8]:
icl.get_vaccine_admin()

,date,manufacturer,region_code,age_group,males,females,first_dose,second_dose,previously_infected,extra_dose,NUTS1_code,NUTS2_code,ISTAT_region_code,region
0,2020-12-27,Pfizer/BioNTech,ABR,20-29,1,1,2,0,0,0,ITF,ITF1,13,Abruzzo
1,2020-12-27,Pfizer/BioNTech,ABR,30-39,1,4,5,0,0,0,ITF,ITF1,13,Abruzzo
2,2020-12-27,Pfizer/BioNTech,ABR,40-49,1,8,9,0,0,0,ITF,ITF1,13,Abruzzo
3,2020-12-27,Pfizer/BioNTech,ABR,50-59,7,6,13,0,0,0,ITF,ITF1,13,Abruzzo
4,2020-12-27,Pfizer/BioNTech,ABR,60-69,12,4,16,0,0,0,ITF,ITF1,13,Abruzzo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133431,2021-10-05,Vaxzevria (AstraZeneca),SIC,60-69,1,0,0,1,0,0,ITG,ITG1,19,Sicilia
133432,2021-10-05,Vaxzevria (AstraZeneca),TOS,70-79,0,1,0,1,0,0,ITI,ITI1,9,Toscana
133433,2021-10-05,Vaxzevria (AstraZeneca),UMB,30-39,1,0,0,1,0,0,ITI,ITI2,10,Umbria
133434,2021-10-05,Vaxzevria (AstraZeneca),VEN,60-69,3,1,0,4,0,0,ITH,ITH3,5,Veneto
133435,2021-10-05,Vaxzevria (AstraZeneca),VEN,70-79,2,0,0,2,0,0,ITH,ITH3,5,Veneto

### get_vaccine_admin_summary

Returns a summary version of the DataFrame about COVID-19 vaccine administration in Italy (the latter can be called with get_vaccine_admin)

In [9]:
icl.get_vaccine_admin_summary()

,date,region_code,total,males,females,first_dose,second_dose,previously_infected,extra_dose,NUTS1_code,NUTS2_code,ISTAT_region_code,region
0,2021-02-07,MOL,67,32,35,20,47,0,0,ITF,ITF2,14,Molise
1,2021-08-27,PIE,17514,9352,8162,7558,9295,661,0,ITC,ITC1,1,Piemonte
2,2021-07-22,LAZ,61234,30594,30640,28392,31231,1611,0,ITI,ITI4,12,Lazio
3,2021-09-01,LOM,60238,32366,27872,30534,25967,3737,0,ITC,ITC4,3,Lombardia
4,2021-09-21,VDA,384,212,172,107,264,13,0,ITC,ITC2,2,Valle d'Aosta / Vallée d'Aoste
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5859,2021-04-01,ABR,5627,2520,3107,3423,2120,84,0,ITF,ITF1,13,Abruzzo
5860,2021-06-15,CAM,18691,9096,9595,10961,7426,304,0,ITF,ITF3,15,Campania
5861,2021-07-25,UMB,7311,3852,3459,1163,6100,48,0,ITI,ITI2,10,Umbria
5862,2021-02-21,SIC,5169,2501,2668,5031,107,31,0,ITG,ITG1,19,Sicilia
5863,2021-06-13,TOS,24625,12357,12268,22541,1660,424,0,ITI,ITI1,9,Toscana

### get_vaccine_ages

Returns a DataFrame about COVID-19 vaccine administrations in Italy, divided per age group.

In [10]:
icl.get_vaccine_ages()

,age_group,total,males,females,first_dose,second_dose,previously_infected,extra_dose,last_update
0,12-19,5917123,3021051,2896072,3113825,2709123,93797,378,2021-10-06
1,20-29,9388121,4878618,4509503,4892097,4310068,183294,2662,2021-10-06
2,30-39,9953608,5094323,4859285,5198505,4560385,189442,5276,2021-10-06
3,40-49,13184068,6510437,6673631,6793958,6113280,264865,11965,2021-10-06
4,50-59,15320374,7491873,7828501,7866696,7100905,329175,23598,2021-10-06
5,60-69,12587389,6094087,6493302,6471858,5850065,233087,32379,2021-10-06
6,70-79,10679209,5009295,5669914,5368147,5113068,163902,34092,2021-10-06
7,80-89,6945451,2881310,4064141,3436294,3364760,81158,63239,2021-10-06
8,90+,1586038,472099,1113939,792713,761940,20483,10902,2021-10-06

### get_vaccine_deliveries

Returns a DataFrame about COVID-19 vaccine deliveries in Italy.

In [11]:
icl.get_vaccine_deliveries()

,region_code,manufacturer,number_of_doses,date_of_delivery,NUTS1_code,NUTS2_code,ISTAT_region_code,region
0,ABR,Pfizer/BioNTech,135,2020-12-27,ITF,ITF1,13,Abruzzo
1,ABR,Pfizer/BioNTech,7800,2020-12-30,ITF,ITF1,13,Abruzzo
2,ABR,Pfizer/BioNTech,3900,2021-01-05,ITF,ITF1,13,Abruzzo
3,ABR,Pfizer/BioNTech,3900,2021-01-07,ITF,ITF1,13,Abruzzo
4,ABR,Pfizer/BioNTech,3900,2021-01-11,ITF,ITF1,13,Abruzzo
...,...,...,...,...,...,...,...,...
4836,VEN,Moderna,35800,2021-09-22,ITH,ITH3,5,Veneto
4837,VEN,Pfizer/BioNTech,108810,2021-09-22,ITH,ITH3,5,Veneto
4838,VEN,Pfizer/BioNTech,4,2021-09-24,ITH,ITH3,5,Veneto
4839,VEN,Moderna,110400,2021-09-29,ITH,ITH3,5,Veneto
4840,VEN,Pfizer/BioNTech,270270,2021-09-29,ITH,ITH3,5,Veneto

### get_vaccine_summary

Returns a DataFrame with a summary of COVID-19 vaccines deliveries and administrations in Italy.

In [12]:
icl.get_vaccine_summary()

,region_code,administered_doses,delivered_doses,administration_percent,last_update,NUTS1_code,NUTS2_code,ISTAT_region_code,region
0,ABR,1875153,2252779,83.2,2021-10-06,ITF,ITF1,13,Abruzzo
1,BAS,805573,926135,87.0,2021-10-06,ITF,ITF5,17,Basilicata
2,CAL,2488500,2871034,86.7,2021-10-06,ITF,ITF6,18,Calabria
3,CAM,7834379,9180875,85.3,2021-10-06,ITF,ITF3,15,Campania
4,EMR,6540029,7247176,90.2,2021-10-06,ITH,ITH5,8,Emilia-Romagna
5,FVG,1669278,2005401,83.2,2021-10-06,ITH,ITH4,6,Friuli-Venezia Giulia
6,LAZ,8373009,10180169,82.2,2021-10-06,ITI,ITI4,12,Lazio
7,LIG,2178436,2555985,85.2,2021-10-06,ITC,ITC3,7,Liguria
8,LOM,15108901,17113107,88.3,2021-10-06,ITC,ITC4,3,Lombardia
9,MAR,2129170,2479376,85.9,2021-10-06,ITI,ITI3,11,Marche
10,MOL,451739,503045,89.8,2021-10-06,ITF,ITF2,14,Molise
11,PAB,669046,782173,85.5,2021-10-06,ITH,ITH1,4,Provincia Autonoma Bolzano / Bozen
12,PAT,769069,878030,87.6,2021-10-06,ITH,ITH2,4,Provincia Autonoma Trento
13,PIE,6099788,7052078,86.5,2021-10-06,ITC,ITC1,1,Piemonte
14,PUG,5868325,6800651,86.3,2021-10-06,ITF,ITF4,16,Puglia
15,SAR,2392518,2748675,87.0,2021-10-06,ITG,ITG2,20,Sardegna
16,SIC,6405529,7559331,84.7,2021-10-06,ITG,ITG1,19,Sicilia
17,TOS,5517629,6089924,90.6,2021-10-06,ITI,ITI1,9,Toscana
18,UMB,1281599,1453017,88.2,2021-10-06,ITI,ITI2,10,Umbria
19,VDA,168650,191150,88.2,2021-10-06,ITC,ITC2,2,Valle d'Aosta / Vallée d'Aoste
20,VEN,6935061,8013208,86.5,2021-10-06,ITH,ITH3,5,Veneto